Bump .NET versions and fix docker build script
tareqimbasher/NetPad pull request #213
Opened 2024-06-13 07:53 UTC by Deliay

This pull request includes these changes:

- Bump .NET to 8.0 and bump almost dependencies to latest version
- Fix & enhance docker build script
- Support launching the OmniSharp server by `dotnet exec OmniSharp.dll` due to the container limitation

2024-06-21 12:30 UTC, tareqimbasher commented
Thank you @Deliay. A rather large refactor is under way on the `solution-refactor` branch, including the upgrade to .NET 8. I will hold off on this PR until that is concluded, in a week or so, since it makes large sweeping changes. Once that's done I will revisit the changes introduced here and let you know.

Thanks for the work on the docker script, I haven't really maintained it at all. I appreciate the contribution.

2024-06-30 12:58 UTC, tareqimbasher commented
Update: PR #211 is merged into main. I will be reviewing the changes here soon to see how it needs to change

2024-07-04 14:16 UTC, tareqimbasher commented on src/Apps/NetPad.Apps.App/appsettings.Development.json
> +    "Urls": "http://0.0.0.0:57940",
Binding to `0.0.0.0` here is a security risk if the machine running NetPad is exposed to an untrusted network. Instead we can have the docker script create an `appsettings.Local.json` that overrides that setting and sets it to `0.0.0.0`. NetPad will use a `appsettings.Local.json` file if one exists.

2024-07-04 15:07 UTC, tareqimbasher requested changes

2024-07-04 15:10 UTC, tareqimbasher commented
@Deliay I requested some changes before merging the PR. 

In addition let's hold off on commit ([Bump .NET to 8 and bump dependencies to latest version](https://github.com/tareqimbasher/NetPad/pull/213/commits/0d0324afe2b41b24be14feb089b436cca16f01eb)). The package upgrade has a little more to it, especially related to the swagger generated API client. For .NET 8 I want to run some tests on my end to make sure everything still works with that upgrade so I'll go ahead and update to .NET 8 in a later PR once I've validated it. Can you also revert the change to v8 in the README introduced in `ac357ba`.

Lastly, the change that you introduced in ([Support lanuch OmniSharp server via 'dotnet exec OmniSharp.dll'](https://github.com/tareqimbasher/NetPad/pull/213/commits/63e7c0c56114df30dd85badbe0e862c1574a0e98)) did you test this still works when running the app without docker?

2024-10-04 17:43 UTC, Jogai commented
@tareqimbasher would you be interested in another pr mainly for fixing the docker file? I have a a working dockerfile on my pc that uses a multistage build.

2024-10-08 01:19 UTC, tareqimbasher commented
@Jogai yes I would be interested. Thanks for the contribution!

2025-02-25 18:33 UTC, closed without merging